### ISSUE TITLE
Cannot use the "date" field

### ISSUE THREAD

**Issue by HarleySalas** [payloadcms/payload-3.0-alpha-demo#10]
### Describe the Bug

  Upon using a date field, I get a black screen, with the following console error:

```
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `DateTime`.
```

### To Reproduce

Put a date field in any collection

### Payload Version

3.0.0-alpha.34

### Adapters and Plugins

@payloadcms/db-postgres@3.0.0-alpha.34

**Comment by AlessioGr** [comment]
Fixed in alpha.41 :)
