### ISSUE TITLE
DevTools "Warning: Extra attributes from the server: class"

### ISSUE THREAD

**Issue by HarleySalas** [payloadcms/payload-3.0-alpha-demo#13]
On every admin page, this error is present. 

![image](https://github.com/payloadcms/payload-3.0-alpha-demo/assets/38236585/abd5e629-efb8-4580-83fc-cd85a39d7911)

I believe it could be impacting things like these unexpected color issues?
![image](https://github.com/payloadcms/payload-3.0-alpha-demo/assets/38236585/7a6858db-98e6-4dbc-b756-500619e78286)

I'm using yarn 1.22.21, no turbo pack

Not sure what, or if it's urgently effecting anything for certain, but I didn't see an issue for it, so 😅

**Comment by jmikrut** [comment]
We are on it!

I haven’t seen this at all yet, so we might benefit from asking you a few questions on Discord if you’re up for it so that we can reproduce

**Comment by HarleySalas** [comment]
I could have **sworn** I replied to this earlier with some notes; I do not see that comment now though.

In any case,  I tried adding v3 myself, as opposed to cloning the alpha-demo. I combed through and I'm fairly certain that everything is nearly an exact match. However, the issue persists in [this repo](https://github.com/bold-media/boldmedia) for me. Upon cloning the alpha-demo myself, I do **not** have this issue. So, there must be something I've done wrong, but I can't imagine what it is... The `(payload)` folder is even copy pasted from the alpha-demo. I'd call it user error and forget about it, but I also imagine I won't be the only one to uncover this issue. Maybe it is something blatantly obvious, but I've certainly missed it after quite a few look overs.

**Comment by JarrodMFlesch** [comment]
Background colors were due to NextJS default styles appearing in the admin panel. I have added some overrides to the templates in the admin panel and those will fix these bg color issues, in [this PR](https://github.com/payloadcms/payload/pull/5289).

**Comment by JarrodMFlesch** [comment]
I am not exactly sure where the extra attribute `class` is coming from though 🤔

**Comment by HarleySalas** [comment]
> I am not exactly sure where the extra attribute `class` is coming from though 🤔 

Were you able to clone the repo and reproduce the same error?

**Comment by JarrodMFlesch** [comment]
@HarleySalas yes I was able to.

**Comment by JarrodMFlesch** [comment]
@HarleySalas ok so, you just need to adjust your folder structure a little bit. There are conflicting RootLayouts in your repo, you will need to separate your app into its own group folder. In the alpha demo repo we use a `/app/(app)` folder.

Something like this:

![CleanShot 2024-03-12 at 9  37 20](https://github.com/payloadcms/payload-3.0-alpha-demo/assets/30633324/48aaa485-a91d-4153-a27f-ec1c3c4cd8b8)
