### ISSUE TITLE
Dev server stops when specifying custom auth strategy

### ISSUE THREAD

**Issue by ikenox** [payloadcms/payload-3.0-alpha-demo#14]
1. add the following configuration to `payload.config.ts`

```typescript
  auth: {
    disableLocalStrategy: true,
    strategies: [
      {
        name: 'default',
        authenticate: async () => {
          return null;
        },
      },
    ],
  },
```

2. start dev server and open `http://localhost:3000/admin`
3. The server stops with the following error message
    ```
    ERROR: 1: Collection "admins" > "auth.strategies[0]" does not match any of the allowed types
    ```

**Comment by ikenox** [comment]
- Schema requires `strategy` field https://github.com/payloadcms/payload/blob/9674f4e/packages/payload/src/collections/config/schema.ts#L96-L107
-  But `AuthStrategy` defines `authenticate` field instead of `strategy` field https://github.com/payloadcms/payload/blob/9674f4e7397677afba552c7970a5616d79090994/packages/payload/src/auth/types.ts#L105

**Comment by PatrikKozak** [comment]
Hey @ikenox - good find! Thank you! 

Got a PR open [here](https://github.com/payloadcms/payload/pull/5293) that fixes this issue. Will be merged and deployed shortly!
