### ISSUE TITLE
@payloadcms/plugin-cloud-storage AWS.S3 is undefined

### ISSUE THREAD

**Issue by Livog** [payloadcms/payload-3.0-alpha-demo#15]
I encountered an issue while working with the alpha version of `@payloadcms/plugin-cloud-storage`. Initially, everything appeared to function correctly until I attempted to upload or delete files. At that point, I received the following error message:

<img width="1604" alt="Screenshot 2024-03-09 at 08 20 03" src="https://github.com/payloadcms/payload-3.0-alpha-demo/assets/6104911/ff0d3e47-8939-46ef-a887-abf5dcedc532">

To troubleshoot, I dived into `@payloadcms/plugin-cloud-storage/dist/adapters/s3/index.js` and inserted a `console.log` for `AWS.S3`. At this point, `AWS.S3` was undefined, which indicated the module wasn't being properly recognized or instantiated.

<img width="1499" alt="Screenshot 2024-03-09 at 08 20 28" src="https://github.com/payloadcms/payload-3.0-alpha-demo/assets/6104911/2e939884-c0ce-4cb1-9979-ad31fc082490">

I then decided to install `@aws-sdk/client-s3` directly into my project's local repository. After doing so, `AWS.S3` became defined, and the issue was resolved, enabling both uploading and deleting functionalities to work as expected.

Upon reviewing the package dependencies, I noticed that `@aws-sdk/client-s3` is listed as a dev dependency within `@payloadcms/plugin-cloud-storage`. Although I'm not certain, this could potentially be related to the issue. Currently, the workaround I'm employing is to explicitly install `@aws-sdk/client-s3` in the local repository. 

For context, I am using `pnpm` version 8.14.3. This solution might be helpful for anyone facing a similar issue or for investigating the cause further.

**Comment by AlessioGr** [comment]
It's actually expected to install that dependency, as outlined in the plugin-cloud-storage package readme. That way we don't have to ship with peerDeps of S3, GCS AND Azure, even if you're only using S3.

The webpack error sucks though, I made an improvement to the plugin-cloud-storage package which now throws a "proper" error, telling you that those packages need to be installed. Will be live in the next version!
