### ISSUE TITLE
Access Control not working as expected

### ISSUE THREAD

**Issue by HarleySalas** [payloadcms/payload-3.0-alpha-demo#16]
In a collection, setting the following will not hide the collection from the admin panel. If I recall correctly, access.admin is meant to hide the collection for specific roles, correct?

To test it, I simply set the following:

```
access: {
    admin: () => false,
}
```

However, it still shows up for all roles.

for `access.create`, I for example has it set to true, which allowed any user to create users. Then, I changed it to the following:
```
create: ({ req }) => checkRole(["admin"], req.user),
```
Yet, I still had the option to create users, until I restarted my dev server (not a prod issue I guess, but I believe we should not be required to restart dev server?).

For `access.read`, I tested it with the same sort of function that is in the access control guide video within the docs; `adminOrSelf`, where you should be able to read the user if you are an admin, OR the document belongs to the currently logged in user. However, the Users collection was still visible **and** it allowed me to click on and visit any user (read), which I believe is not expected.

Lastly, when I simply set the following;
```
 read: () => false,
```

It finally made it so that I could not see the `Users` collection, which is expected in this case. However, when I visit my own profile with the profile icon in the top right, breadcrumbs are visible at the top of the layout. I can then click `Users` and read the entire table of all users. With the column filter, I can view the data in all roles (and effectively read it). I get a 404 when I try to visit one of the user's document pages, which is ideal, I guess? However, it doesn't really matter, because as I said, they are still able to somehow view that data inside of the collection table.

Field level access control seems completely broken.

I hope everything I've said makes sense. Overall, I find access control to feel quite wonky and I'm not sure it's in a usable state.

**Comment by jmikrut** [comment]
Hey there!

Here are some answers for you:

```
access: {
    admin: () => false,
}
```

This is used only for auth-enabled collections, to restrict _**who can log into the admin panel, and who cannot.**_ It is not used to hide other non-auth-enabled collections from users. [Here are the docs](https://payloadcms.com/docs/access-control/collections#admin) for that method.

> Yet, I still had the option to create users, until I restarted my dev server (not a prod issue I guess, but I believe we should not be required to restart dev server?).

This should be fixed on latest alpha!

> Field level access control seems completely broken.

This should also be fixed, but please let me know if you spot anything else there. I tested and HMR works as well with field-level access control. But it was pretty wild for a sec there. Prob some bugs here and there, but I believe it is now working much better.

Keep an eye out for the next alpha release (publishing now) and give it a shot!
