### ISSUE TITLE
Error on save is not being thrown when it should be

### ISSUE THREAD

**Issue by HarleySalas** [payloadcms/payload-3.0-alpha-demo#23]
In other issues, I have noted that certain field types do not get saved.  See [#19 ](https://github.com/payloadcms/payload-3.0-alpha-demo/issues/19) and [#20](https://github.com/payloadcms/payload-3.0-alpha-demo/issues/20), perhaps more.

However, there is no error that is thrown for those instances when those fields don't save and it prevents other fields from being written to when fields that are not working properly are saved.

For example, for those *broken* field types, I may have `required: true` and will fill these fields out, despite knowing that they will not work. I will then fill out fields that *should* work and those fields are not saved, since those "required" fields were not properly saved. I suppose that is the behavior we'd expect-- a required field wasn't saved, so the entire document should not be saved.

However, it still provides us with a success toast.

Feel free to just close and throw this one out, as perhaps resolving those issues all together will solve this... But, perhaps there is something inherently wrong with error handling as well.

**Edit:**
Perhaps its better to see #25. Sorry for a bit of gibberish above. Issue 25 should cover 19 and 20 and I decided to leave this open, as I believe that despite the issues with drizzle and saving documents, an error should still be thrown; I don't think I should be getting success toast messages.

**Comment by JessChowdhury** [comment]
Hi @HarleySalas, thanks for raising this! I have caught several error UI inconsistencies which will be resolved in [this PR](https://github.com/payloadcms/payload/pull/5339). I will leave this issue open until we get the PR merged, then error states should be good to go 👍

**Comment by paulpopus** [comment]
Hey @HarleySalas this should be working now, tested with a richtext, media and text field and the toast should now give the correct error state
