### ISSUE TITLE
Drizzle does not push updates until after dev server is restarted

### ISSUE THREAD

**Issue by HarleySalas** [payloadcms/payload-3.0-alpha-demo#25]
Using pnpm, with postgres, the latest `payload-3.0-alpha-demo` and all packages on `alpha.41`.

It appears that in many instances, such-as with numbers and relationships (closed issues #19 and #20), these fields are not saving until I restart my dev server, which then triggers `drizzle push`, I assume.

I believe the expected behavior is that you should not have to restart your dev server in order to reflect config changes? At least this is what I've heard. It also doesn't throw any errors when these saves fail. They essentially appear to save the data, I get a success notification banner, but when I refresh the page, the data is gone. (#23 references errors not being thrown)

**Comment by jmikrut** [comment]
Yes, you should not have to restart your server. We are gonna check on this. I think this was fixed with alpha-41 already actually but something else broke. On it!

**Comment by HarleySalas** [comment]
Just a note that perhaps it's not only drizzle. Unsure if considered related, or separate, but I think the entire payload config does not update until server is restarted? For example, if I change a field hook,  even if it's just to `console.log` something, it will not be fired off until dev server restarted.

**Comment by jmikrut** [comment]
Hey @HarleySalas — I just tested this again and it may have been resolved with some other fixes that we've pushed recently, but I do indeed see Drizzle pushing schema updates during dev mode.

Can you update and try again? Let us know!
