### ISSUE TITLE
Cannot change language in user preferences

### ISSUE THREAD

**Issue by galcsikgyozo** [payloadcms/payload-3.0-alpha-demo#34]
Cloned the project (everything on version alpha.46), started it with the postgresAdapter, and went into the account page (`/admin/account`) to change my language from what is selected by default (in my case Hungarian, a.k.a. Magyar) to English, but the select input doesn't seem to work.

Also getting this error in my console:
<img width="1800" alt="Screenshot 2024-03-12 at 15 12 55" src="https://github.com/payloadcms/payload-3.0-alpha-demo/assets/60744669/215d8562-3a5b-487b-95c7-31d5f167ad2a">

**Comment by galcsikgyozo** [comment]
On `3.0.0-alpha.48` the console error is not there anymore, but still can't change language.
Freshly cloned, installed with pnpm, using a clean PostgreSQL database.
Other select inputs created by fields seems to work perfectly.


https://github.com/payloadcms/payload-3.0-alpha-demo/assets/60744669/ca0c476e-3aab-43f5-85bf-e0f8f6682de1

**Comment by alsherif-khalaf** [comment]
Same issue,  also the localization doesn't work

**Comment by jmikrut** [comment]
This is now fixed and will be released in the next alpha!
