### ISSUE TITLE
Documentation change for README.md

### ISSUE THREAD

**Issue by Iseeumhmm** [payloadcms/payload-3.0-alpha-demo#35]
Currently README.md points to `https://github.com/payloadcms/payload` for opening issues.  

I added 3 issues there yesterday related to the V3 alpha repo: 

  - [5300](https://github.com/payloadcms/payload-3.0-alpha-demo/issues/41)
  - [5299](https://github.com/payloadcms/payload-3.0-alpha-demo/issues/42
) 
 - [5298]( https://github.com/payloadcms/payload-3.0-alpha-demo/issues/43)

**Comment by jmikrut** [comment]
Hey @Iseeumhmm thank you! Fixed.
