### ISSUE TITLE
Filter options and RowLabel not working

### ISSUE THREAD

**Issue by paulpopus** [payloadcms/payload-3.0-alpha-demo#36]
filterOptions are next actions? I added "use server" and made them async for now. It's been a while since I used Next last time, so will need a refresher.

Some of my custom components, like row labels, are rendered blank. It's the same for the nested-docs plugin breadcrumbs. I need to take a look at how this is handled.

Pulling this info from discord

**Comment by jmikrut** [comment]
This is now all done! Will release another alpha today.
