### ISSUE TITLE
Collection Table/ListView Search does nothing

### ISSUE THREAD

**Issue by HarleySalas** [payloadcms/payload-3.0-alpha-demo#38]
`/admin/collections/[collection]` Search does nothing.

Checked across multiple projects and collections with various configs. All of them do not have search working, so I imagine it doesn't work for anyone? *Should* be quite an reproduction.

Database adapter: Postgres
Package Manager: pnpm
Payload Alpha Version: 48
Node Version: 18.19.0
Using payload-3.0-alpha-demo example ✅

**Comment by JarrodMFlesch** [comment]
This has been fixed, verified working on alpha demo, using `3.0.0-alpha.54`, closing. Thanks for reporting!
