### ISSUE TITLE
Unable to save a block value that uses a row nested in a group

### ISSUE THREAD

**Issue by jake-a-wood** [payloadcms/payload-3.0-alpha-demo#46]
I found that as I was attempting a similar situation to the one below:

```typescript
import { Block } from 'payload/types'

const Banner: Block = {
  slug: 'Banner', // required
  imageURL: 'https://placehold.co/600x400',
  imageAltText: 'A nice thumbnail image to show what this block looks like',
  interfaceName: 'BannerBlock', // optional
  fields: [
    {
      type: 'group',
      name: 'link',
      fields: [
        {
          type: 'row',
          fields: [
            {
              type: 'text',
              name: 'text',
            },
          ],
        },
      ],
    },
  ],
}

export default Banner
```

That every time I saved, it never actually did so to the database and in fact comes back as a blank field on the response to the save.

**Comment by cuquo** [comment]
it doesn't read existing data too if it helps for this issue

**Comment by spencerxl** [comment]
Same issue with a row nested in an array field. Using the postgres adapter.
No error thrown in the admin panel, but no data saved to the collectionname_arrayname_fieldname table.

**Comment by cuquo** [comment]
with the latest alpha there isn't an error at the moment of saving but it doesn't saves the data

**Comment by JessChowdhury** [comment]
@jake-a-wood @cuquo are you using Postgres or MongoDB?

**Comment by jake-a-wood** [comment]
@JessChowdhury I was using MongoDB

**Comment by JessChowdhury** [comment]
@jake-a-wood thanks for confirming! This appears to be resolved with the latest changes to `alpha` - I will leave this issue open here until we cut a new release and have it working in the demo.
