### ISSUE TITLE
cellData is not being passed to custom cell components

### ISSUE THREAD

**Issue by mcornielje090404** [payloadcms/payload-3.0-alpha-demo#48]
Hello I noticed that custom cells do not seem to have the cell data passed to them. 

I have a simple cell component as shown below used as a colour picker cell.

```js
import type React from "react";
import type { CellComponentProps } from "payload/types";

export const ColourPickerCell: React.FC<CellComponentProps> = ({
  cellData,
}) => {
  if (!cellData) return null;
  
  return (
    <div
      style={{
        border: "solid",
        borderWidth: "2px",
        borderColor: "white",
        borderRadius: "50%",
        height: "2rem",
        width: "2rem",
        backgroundColor: cellData as string,
      }}
    />
  );
};
```

I decided to log out the props being used to determine the reason my cells would never render and the props passed to the component are the following:

```json
{
    "name": "textColour",
    "blocks": false,
    "fieldType": "text",
    "isFieldAffectingData": true,
    "label": "Text Colour"
}
```

This is the object being used to set the custom cell component

```js
admin: {
  components: {
	  Field: ColourPickerField,
	  Cell: ColourPickerCell,
  },
},
```

As you can see the cellData is never actually passed so the field will not render (in my instance)

**Comment by jacobsfletch** [comment]
Hey @mcornielje090404, custom cell components are now pre-rendered on the server, which have no data at compile time. You now have to use the `useTableCell` hook to get this. I'll update the types in 3.0 shortly to reflect this change. Here's an example of how to migrate:

```
'use client'
import React from 'react'
import type { CellComponentProps } from 'payload/types'
import { useTableCell } from '@payloadcms/ui/elements/Table'

export const CustomCell: React.FC<CellComponentProps> = (props) => {
  const context = useTableCell()
  return <div>{`Custom cell: ${context.cellData || 'No data'}`}</div>
}
```
