### ISSUE TITLE
Generating types fails with package imports from next and @payloadcms/ui

### ISSUE THREAD

**Issue by mcornielje090404** [payloadcms/payload-3.0-alpha-demo#50]
When generating types the script fails when external packages are used within custom files.

I have noticed this occur with the following packages:

- next/headers
- next/navigation
- @payloadcms/ui

I imagine there will be more however these are the ones I have found. 

An example of the error shown:
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/{{MY DIRECTORY PATH}}/node_modules/@payloadcms/ui/dist/exports/forms.js' imported from /{{MY DIRECTORY PATH}}/src/components/admin-fields/ColourPicker/ColourPickerField.tsx
    at finalizeResolution (node:internal/modules/esm/resolve:264:11)
    at moduleResolve (node:internal/modules/esm/resolve:917:10)
    at defaultResolve (node:internal/modules/esm/resolve:1130:11)
    at nextResolve (node:internal/modules/esm/hooks:749:28)
    at resolve (file:///{{MY DIRECTORY PATH}}/node_modules/.pnpm/payload@3.0.0-alpha.48_@swc+core@1.4.8_@swc+types@0.1.6/node_modules/payload/dist/bin/register/index.js:59:12)
    at nextResolve (node:internal/modules/esm/hooks:749:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:237:30)
    at handleMessage (node:internal/modules/esm/worker:199:24)
    at Immediate.checkForMessages (node:internal/modules/esm/worker:141:28)
    at process.processImmediate (node:internal/timers:478:21) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///{{MY DIRECTORY PATH}}/node_modules/@payloadcms/ui/dist/exports/forms.js'
}
```

The component this issue is pointing to is:
```ts
"use client";

import type React from "react";
import {
  Label,
  type TextFieldProps,
  useField,
  Text,
} from "@payloadcms/ui/forms";
import { validateHexColour } from "./utils/validateHexColour";
import { HexColorPicker } from "react-colorful";

export const ColourPickerField: React.FC<TextFieldProps> = ({
  path,
  label,
  required,
  name,
}) => {
  const { value, setValue } = useField({
    path,
    validate: validateHexColour,
  });

  return (
      <div
        style={{
          display: "flex",
          flexDirection: "column",
          gap: "1rem",
        }}
      >
        <Label label={label} htmlFor={path} required={required} />
        <HexColorPicker
          style={{ display: "flex", width: "100%" }}
          color={(value as string) ?? ""}
          onChange={setValue}
        />
        <Text name={name} path={path} />
      </div>
    );
};
```

**Comment by mcornielje090404** [comment]
Also noticing this when the slate editor is part of my config ^

**Comment by willviles** [comment]
I'm experiencing the same issues with type generation. Using node `18.19.1` (`lts/hydrogen`).

One interesting thing to note is that external packages imported using the default import seem to work, however, destructuring any imports fail. In my codebase:

```ts
// This works ✅

import _ from 'lodash'

_.merge(fieldConfig, overrides)
```

```ts
// Errors ❌

import { merge } from 'lodash'

/* import { merge } from "lodash";
            ^^^^^
SyntaxError: The requested module 'lodash' does not provide an export named 'merge'
at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
at async ModuleJob.run (node:internal/modules/esm/module_job:191:5)
at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)
at async bin (file:///path/to/my/project/node_modules/.pnpm/payload@3.0.0-alpha.48_@swc+core@1.4.8_@swc+types@0.1.6/node_modules/payload/dist/bin/index.js:10:27)
*/ 

merge(fieldConfig, overrides)
```

**Comment by willviles** [comment]
Also, trying to import any module that isn't compiled to js or cjs seems to be an issue too. 

In my monorepo, I don't use any build steps, instead just favouring `.ts/.mts` exports and then throw them at the Next.js compiler using `transpilePackages`.

It doesn't work regardless of whether the imported module is `"type": "module"`, or whether the file extension is `.ts` or `.mts`.

```ts
// Errors ❌

import { toSlug } from '@repo/helpers/string'

/* node:internal/process/promises:288
triggerUncaughtException(err, true / fromPromise /);
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /path/to/my/project/packages/helpers/string.ts
at new NodeError (node:internal/errors:405:5)
at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:136:11)
at defaultGetFormat (node:internal/modules/esm/get_format:182:36)
at defaultLoad (node:internal/modules/esm/load:101:20)
at nextLoad (node:internal/modules/esm/hooks:864:28)
at load (file:///path/to/my/project/node_modules/.pnpm/payload@3.0.0-alpha.48_@swc+core@1.4.8_@swc+types@0.1.6/node_modules/payload/dist/bin/register/index.js:91:16)
at nextLoad (node:internal/modules/esm/hooks:864:28)
at Hooks.load (node:internal/modules/esm/hooks:447:26)
at handleMessage (node:internal/modules/esm/worker:196:24)
at checkForMessages (node:internal/modules/esm/worker:138:28) {
code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
*/
```

**Comment by mcornielje090404** [comment]
Hey @willviles I've noticed tsx works fine when using .ts files. I believe the 'Unknown file extension ".ts"' Error is indeed a ts-node problem, I face the same working with ts-node. I recommend switching over to [tsx](https://github.com/privatenumber/tsx#readme).

**Comment by willviles** [comment]
Hey @mcornielje090404, thanks for the insight. I've switched over to tsx and the `Unknown file extension ".ts"` errors disappear when running type generation script like this:

```bash
bun tsx ./node_modules/payload/bin.js generate:types"
```

However, I'm still running into the issue of non-default exports of dependencies not being recognised by the custom Payload loader. Can anyone else replicate this?

**Comment by mcornielje090404** [comment]
I believe you are correct the issue I'm facing above is more specifically to do with named imports

**Comment by jmikrut** [comment]
One thing I'm thinking here is that Payload configs are now ESM, so you need to import a bit differently.

And errors won't show themselves within Next.js, because Next.js runs in `bundler` mode, meaning it doesn't really use Node resolution in order to load modules - instead, it uses Webpack / Turbopack which resolves modules differently (and is much more forgiving).

But in `payload generate:types`, at least right now, we don't use that same module resolution strategy. So where in Next.js, you could import something like this:

```
import { redirect } from 'next/navigation'
```

This works because of Webpack / Turbopack and won't surface errors while running dev / prod. 

But in the ESM land, you'd have to do:

```
import { redirect } from 'next/navigation.js' // add the .js
```

You may be able to work around these issues for now, but we also might be able to solve this for you. We are working on improving our bin script loader so that it is more forgiving for imports (like Webpack / Turbopack.)

Does this all make sense? 

Related:

https://github.com/payloadcms/payload-3.0-alpha-demo/issues/56

**Comment by jmikrut** [comment]
Hey all, in the next alpha version, you should be good now. We made some improvements to our loader which is used in the `bin` scripts (`generate:types`, etc.)

Gonna close this now but if you find anything else, please let me know and we will re-open!
