### ISSUE TITLE
Missing Last Modified and Created

### ISSUE THREAD

**Issue by denolfe** [payloadcms/payload-3.0-alpha-demo#53]
These fields are not showing values in the UI
<img width="584" alt="CleanShot 2024-03-22 at 13 17 38" src="https://github.com/payloadcms/payload-3.0-alpha-demo/assets/65888/c97e932c-4ae0-4457-9779-cd590d3d9077">

**Comment by paulpopus** [comment]
Looks like this is now fixed on latest alpha branch

**Comment by paulpopus** [comment]
Ha reopening!

This is fixed only for the main tab

**Comment by paulpopus** [comment]
Fixed in https://github.com/payloadcms/payload/pull/5477
