### ISSUE TITLE
Breadcrumbs flicker on navigation

### ISSUE THREAD

**Issue by denolfe** [payloadcms/payload-3.0-alpha-demo#54]
When clicking between collections, there is some flicker on the breadcrumbs.

https://github.com/payloadcms/payload-3.0-alpha-demo/assets/65888/2c3edbe6-94ba-47ae-8ace-bdbfef54716a

**Comment by denolfe** [comment]
Looks like this happens moving between pages as well for the header text.

https://github.com/payloadcms/payload-3.0-alpha-demo/assets/65888/eb53db33-5086-407a-ab3b-e6c610d6de7f

**Comment by paulpopus** [comment]
Not seeing this happen again across a few test suites, closing for now
