### ISSUE TITLE
Unable to run Local API script

### ISSUE THREAD

**Issue by denolfe** [payloadcms/payload-3.0-alpha-demo#56]
Attempting to run a script that uses the Local API currently errors due to scss files being pulled in.

Example script:

```ts
import { getPayload } from 'payload'
import config from '@payload-config'

async function run() {
  const payload = await getPayload({ config })

  const pages = await payload.find({
    collection: 'pages',
  })

  console.log({ docs: pages.docs })
}

run().catch(console.error)
```

Executed with `tsx`:

`pnpm tsx src/scripts/test.ts`

Output:
```
node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".scss" for /Users/elliot/dev/payload-3.0-alpha-demo/node_modules/.pnpm/@payloadcms+richtext-lexical@3.0.0-alpha.49_@lexical+clipboard@0.13.1_@payloadcms+next@3.0.0-_7tqibovp2jh2cubsnjoww2s7cm/node_modules/@payloadcms/richtext-lexical/dist/field/lexical/theme/EditorTheme.scss
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at new NodeError (node:internal/errors:405:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:136:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:182:36)
    at defaultLoad (node:internal/modules/esm/load:101:20)
    at nextLoad (node:internal/modules/esm/hooks:864:28)
    at Z (file:///Users/elliot/dev/payload-3.0-alpha-demo/node_modules/.pnpm/tsx@4.7.1/node_modules/tsx/dist/esm/index.mjs:5:1618)
    at nextLoad (node:internal/modules/esm/hooks:864:28)
    at Hooks.load (node:internal/modules/esm/hooks:447:26)
    at handleMessage (node:internal/modules/esm/worker:196:24)
    at Immediate.checkForMessages (node:internal/modules/esm/worker:138:28)
    at process.processImmediate (node:internal/timers:476:21) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```

**Comment by valerioleo** [comment]
This is one problem I am facing as well. 
One of the most awaited changes for me was the separation between the backend and frontend code from payload so that the Local API can be used _à la prisma_ to interact with the DB. 

Unfortunately, the config file still pulls in some CSS code and prevents me from using payload in simple node scripts.

**Comment by digitalbase** [comment]
@valerioleo we were hoping for the same too. No success just yet.

We want to use the localAPI from Payload 3.x in a production website while we keep the CMS interface on 2.x until it's more stable (and all the plugins, add-ons, and all the other things we tuned is ported and 3x is on final API). 

To proceed with this (localAPI is super useful on nextjs side) we're trying to bootstrap payload with a lightweight Payload config with mainly primitives (collections, globals, fields). We're almost done with this and have some minor issues (hook support and some small bugs) to fix.

Perhaps that's an approach you could use?

**Comment by jmikrut** [comment]
We have some plans for this and are going to release some things in the near future which will make this all super easy - @denolfe and I will update here shortly!

**Comment by denolfe** [comment]
Fixed. 

https://github.com/payloadcms/payload-3.0-alpha-demo/commit/ec95e415c60fe9f89e998ef13e6c24da1aeb8b26

Example script can be run with `pnpm standalone-script`

**Comment by tresorama** [comment]
Is possible to make it works with v2 ? Or only v3?

**Comment by xHomu** [comment]
You can use Local API in v2, but not as a standalone since it's bundled with all the express middleware stuff.

**Comment by tresorama** [comment]
If someone need a typesafe REST API  for payload v2 they can look at [payload-rest-client](https://www.npmjs.com/package/payload-rest-client)
