### ISSUE TITLE
Link feature not working in Lexical

### ISSUE THREAD

**Issue by goodallman** [payloadcms/payload-3.0-alpha-demo#58]
Getting error: Cannot read properties of undefined (reading 'fields.url') 

This is when I am trying to add link to Lexical Rich Text via the drawer component. More in video:

Also noticed that something weird is happening with the state of fields in view, when you first add them. When you start typing, everything gets deleted and the field is out of focus (maybe undefined state?), might be related?

https://github.com/payloadcms/payload-3.0-alpha-demo/assets/16398310/afcd0be6-4502-4925-becf-6010639fa8ff

**Comment by goodallman** [comment]
Just a quick update, switching database adapter from postgres so mongo fixed the issue.

**Comment by HarleySalas** [comment]
I don't get the issue shown here; I'm using postgres.

However, I don't get any of the link data populated in my api response.

No matter which type of link I select, this is the data I get:
```
"type": "link",

"fields": {
"doc": null,
"url": "https://",
"newTab": false,
"linkType": "custom"
},
```

`linkType` is always `custom`

Icons are not shown either
![image](https://github.com/payloadcms/payload-3.0-alpha-demo/assets/38236585/aef05d83-90ed-4d67-b8ea-da59dd9bd5d8)

**Comment by AlessioGr** [comment]
Thank you for reporting this! Will be fixed in the next release
