### ISSUE TITLE
Small UI bug: Breadcrumbs on Live Preview editor tab

### ISSUE THREAD

**Issue by galcsikgyozo** [payloadcms/payload-3.0-alpha-demo#59]
On `3.0.0-alpha.49` using PostgreSQL as a database, the breadcrumbs on the "Live Preview" don't display the name of the collection and the title of the page, but an ID instead.

Correctly shown on the **Edit** page:
<img width="1038" alt="Screenshot 2024-03-25 at 14 00 25" src="https://github.com/payloadcms/payload-3.0-alpha-demo/assets/60744669/8f5f580b-c3d2-4e43-bcde-9a8573b35b83">

Incorrectly displayed on **Live Preview** tab:
<img width="1035" alt="Screenshot 2024-03-25 at 14 00 17" src="https://github.com/payloadcms/payload-3.0-alpha-demo/assets/60744669/b81d80f1-aee5-44bf-acfe-a94fc1e394d6">

**Comment by paulpopus** [comment]
Fixed in https://github.com/payloadcms/payload/pull/5478
