### ISSUE TITLE
Error when executing the command `npm run payload migrate:create`

### ISSUE THREAD

**Issue by vab1997** [payloadcms/payload-3.0-alpha-demo#60]
I'm following this steps, in the step 3 when I want to create a migration
![image](https://github.com/payloadcms/payload-3.0-alpha-demo/assets/54491743/18eb36a3-2eee-4ce4-bcd1-0f2fffd1e073)

throw an error in the console
![image](https://github.com/payloadcms/payload-3.0-alpha-demo/assets/54491743/92b85c3c-e276-42f1-b9da-2254b83a78c8)

The config in payload config is:
![image](https://github.com/payloadcms/payload-3.0-alpha-demo/assets/54491743/a77429a3-160f-4fc5-90ab-2588dcc5ffdf)

**Comment by denolfe** [comment]
This has been fixed in latest alpha.
