### ISSUE TITLE
When auth.disableLocalStrategy is true, reset password field still exists

### ISSUE THREAD

**Issue by HarleySalas** [payloadcms/payload-3.0-alpha-demo#64]
My `User` Collection looks like this:
```
export const User: CollectionConfig = {
  slug: "user",
  auth: {
    disableLocalStrategy: true,
    strategies: [
      {
        name: "discord",
        authenticate: discordAuthenticationStrategy,
      },
    ],
  },
...
```

Upon using `disableLocalStrategy: true`, all of the default user fields are removed from my database, including the `password` field. This is of course expected; my own auth does not require a password, it is OAuth only.

However, the UI component to reset password still exists. I imagine there is a way to remove it, but wouldn't it be expected that if the password field doesn't exist, these sort of components should not be present?

![image](https://github.com/payloadcms/payload-3.0-alpha-demo/assets/38236585/344890c1-0d1a-41ed-a7d5-f396727d5f9c)

**Comment by HarleySalas** [comment]
I would also like to note;

I noticed that upon saving data about the current user, it redirects you to the `/admin/logout-inactivity` route. I see you can make that a custom route as well. However, I don't believe all login systems will require this. My custom auth for example is session based and all I need to do upon a user's data changing is to refresh, or revalidate the session data.

Perhaps there are more steps to be done, which aren't documented, or spoken about yet?

**Comment by paulpopus** [comment]
Hey @HarleySalas the issues outline above have been fixed now. Saving data on the user should not redirect anymore either, please let us know if you do encounter any further problems around auth
