### ISSUE TITLE
POTENTIAL BUG - Upload Collections Ignoring Mutated URL - Alpha 54

### ISSUE THREAD

**Issue by mcornielje090404** [payloadcms/payload-3.0-alpha-demo#66]
Hello,

## Summary
I am working with upload collections on alpha version 54 and have noticed that upload collections are not accounting for the new URL I mutate in the afterRead hook on an upload collection. 

## Details

The data returned as seen in the network tab contains the correct url.

```json
"url": {
    "errorPaths": [],
    "initialValue": "{{My mutated URL}}"
    "passesCondition": true,
    "valid": true,
    "value": "{{My mutated URL}}"
}
```

however, when I check to see what URL is being used to fetch the image preview it is still using the local API url:

<img width="720" alt="Screenshot 2024-04-05 at 10 51 12" src="https://github.com/payloadcms/payload-3.0-alpha-demo/assets/90604542/95e9bfab-fe38-45a5-b4bf-2879bbc73ac6">

there is also an error shown in the console stating 'This collection has local storage disabled: organisation-logos' which is expected as I do have local storage disabled however it should not be attempting to fetch from local storage.

## Steps to recreate

- Create an upload collection
- Create an afterRead hook that mutates the returned URL
- The wrong URL will be used

**Comment by JarrodMFlesch** [comment]
Will be fixed when the parent branch is merged in. Thanks for reporting!

[Related commit](https://github.com/payloadcms/payload/commit/503644b6585ccba9daa078c182c3e4e3c4a789b2)
