### ISSUE TITLE
Setting Globals'  access.readVersions to false does not remove the Versions button

### ISSUE THREAD

**Issue by HarleySalas** [payloadcms/payload-3.0-alpha-demo#67]
Using postgres + alpha v55

Upon making a `Globals` document, setting the `GlobalConfig.access.readVersions` to false does not remove the `Versions` button from the layout at the top.

Visting that page also states that you are not logged in.

It should be noted that I am running a custom authentication strategy, but I get this weird page saying that I'm not even logged in. I believe regardless of the authentication type, it should strictly say `Unauthorized`, not that you are not logged in. (If you were to manually navigate to that page in the url bar. I believe the button itself should not be displayed in the layout.)

![image](https://github.com/payloadcms/payload-3.0-alpha-demo/assets/38236585/c9eb3ba5-6377-4415-a235-8c8a8482556e)

**Comment by jacobsfletch** [comment]
I've got a fix for that last part queued up in https://github.com/payloadcms/payload/pull/5734
