### ISSUE TITLE
Extra breadcrumbs entry on  /admin/globals/{global}/versions

### ISSUE THREAD

**Issue by HarleySalas** [payloadcms/payload-3.0-alpha-demo#68]
alpha v55, postgres

when I visit `/admin/globals/{global}/versions`, in the breadcrumbs at the top, there is an additional segment of my global slug. (Listed twice)

![image](https://github.com/payloadcms/payload-3.0-alpha-demo/assets/38236585/6a2ae3ac-5094-4d22-9cbf-e1e9798c4571)

The url when hovering the additional breadcrumb is also undefined in the url
![image](https://github.com/payloadcms/payload-3.0-alpha-demo/assets/38236585/9208afb1-d007-4b9e-a6e6-6ff8fdabe300)
![image](https://github.com/payloadcms/payload-3.0-alpha-demo/assets/38236585/ea0e3e20-6c9d-430a-b7c4-c7ffbb21724d)

**Edit:**
Right... and it also links to `admin/collections/`, instead of `/admin/globals`
This is the case for both breadcrumbs, including the one that does not contain an `undefined` slug.

**Comment by JarrodMFlesch** [comment]
Closed with https://github.com/payloadcms/payload/pull/5744
