### ISSUE TITLE
Generate Types Bug

### ISSUE THREAD

**Issue by Livog** [payloadcms/payload-3.0-alpha-demo#7]
I'm getting these error when running pnpm run generate:types. So first I got error about some module not being installed and then about dotenv, so just tryed installing these to fix the error. Then after that I came to the end bug,  where it looks liket the bin.js isn't ESM yet.

<img width="1166" alt="Screenshot 2024-03-08 at 18 40 37" src="https://github.com/payloadcms/payload-3.0-alpha-demo/assets/6104911/4ec33e1e-9f42-4693-9cf3-3f0b73520618">
<img width="1146" alt="Screenshot 2024-03-08 at 18 40 20" src="https://github.com/payloadcms/payload-3.0-alpha-demo/assets/6104911/d557c9a7-6feb-45ee-bbe8-28c45f6590be">

**Comment by jmikrut** [comment]
This is now fixed! Thank you for reporting!
