### ISSUE TITLE
Making file changes while using Turbopack causes errors

### ISSUE THREAD

**Issue by kendelljoseph** [payloadcms/payload-3.0-alpha-demo#9]
# Error
```
TypeError: Cannot read properties of null (reading 'useContext')
```

- This error occurs strictly when using `pnpm dev --turbo` which enables Turbopack.
- This error occurs after making changes to existing files.

---
To reproduce, run payload with Turbopack, then edit the default collection in the config by adding and saving some code like this:
```javascript
const test = 1; // Add this line of code, then save the file

export default buildConfig({
  ...
});
```

**Comment by jmikrut** [comment]
This is likely a problem with Turbopack but we should see if we can get around it somehow for sure

**Comment by jmikrut** [comment]
Looks like a more recent Next canary has improved this, and I expect further improvements to come as well. Closing in preference to tracking this type of thing on the Turbopack repo instead.
